"""Forensics of X5's holdout failure (ZBA v2), from the saved trade files only: no network, no re-run, no new rule.

    python docs/backtest/zba-v2-forensics.py > docs/backtest/zba-v2-forensics-tables.md

Reads the development and holdout realistic trade CSVs (X5 rows) and prints Markdown tables: each split shows trades,
mean net R, mean gross R, mean cost R, win rate and the share of stop exits, development next to holdout."""
import collections
import csv
import math
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEV = HERE / "ticket-zba-v2-2026-10-09-realistic.csv"
HOLD = HERE / "ticket-zba-v2-holdout-2026-10-10-realistic.csv"


def load(path):
    rows = []
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            if r["variant"] != "X5" or r["filled"] != "True":
                continue
            for k in ("rank", "shares", "side"):
                r[k] = int(r[k])
            for k in ("rel_vol", "level", "R", "spread", "fill", "gross_r", "cost_r", "net_r", "net_r_short"):
                r[k] = float(r[k])
            r["slip"] = (r["fill"] - r["level"]) * r["side"] / r["R"]  # entry beyond the stop level, in R
            r["atr_pct"] = r["R"] / 0.10 / r["fill"]  # ATR14 / price (D = 0.10 x ATR14)
            r["spread_d"] = r["spread"] / r["R"]
            rows.append(r)
    return rows


def t_stat(xs):
    if len(xs) < 2:
        return None
    sd = statistics.stdev(xs)
    return statistics.mean(xs) / (sd / math.sqrt(len(xs))) if sd else None


def cell(rows):
    if not rows:
        return "0 | — | — | — | — | —"
    n = len(rows)
    net = [r["net_r"] for r in rows]
    t = t_stat(net)
    return (f"{n} | {statistics.mean(net):+.3f}{'' if t is None else f' (t {t:+.1f})'} | "
            f"{statistics.mean(r['gross_r'] for r in rows):+.3f} | {statistics.mean(r['cost_r'] for r in rows):.3f} | "
            f"{sum(x > 0 for x in net) / n:.0%} | {sum(r['kinds'] == 'stop' for r in rows) / n:.0%}")


def table(title, key, order, dev, hold, note=""):
    print(f"\n### {title}\n")
    if note:
        print(note + "\n")
    print("| Group | Dev trades | Dev mean net R | Dev gross | Dev cost | Dev win | Dev stop | "
          "Holdout trades | Holdout mean net R | Holdout gross | Holdout cost | Holdout win | Holdout stop |")
    print("|---|" + "---:|" * 12)
    gd, gh = collections.defaultdict(list), collections.defaultdict(list)
    for r in dev:
        gd[key(r)].append(r)
    for r in hold:
        gh[key(r)].append(r)
    for g in order or sorted(set(gd) | set(gh)):
        print(f"| {g} | {cell(gd.get(g, []))} | {cell(gh.get(g, []))} |")


def bucket(edges, labels):
    def f(x):
        for e, lab in zip(edges, labels):
            if x < e:
                return lab
        return labels[-1]
    return f


def concentration(name, rows):
    net = sorted((r["net_r"] for r in rows), reverse=True)
    total, n = sum(net), len(net)
    k1, k5 = max(1, n // 100), max(1, n // 20)
    big = [x for x in net if x >= 5]
    return (f"| {name} | {n} | {total:+.1f} | {sum(net[:k1]):+.1f} | {sum(net[:k5]):+.1f} | {total - sum(net[:k1]):+.1f} | "
            f"{len(big)} ({len(big) / n:.1%}) | {statistics.mean(big) if big else 0:+.2f} | "
            f"{statistics.mean(x for x in net if x < 5):+.3f} | {max(net):+.1f} |")


def monthly(rows):
    m = collections.defaultdict(float)
    for r in rows:
        m[r["day"][:7]] += r["net_r"]
    return m


def main():
    dev, hold = load(DEV), load(HOLD)
    print(f"# X5 forensics tables (generated by docs/backtest/zba-v2-forensics.py)\n\nDev trades {len(dev)}, holdout "
          f"trades {len(hold)}. Columns per period: trades, mean net R (t), mean gross R, mean cost R, win rate, "
          "share of exits at the stop.")
    table("All", lambda r: "all", ["all"], dev, hold)
    table("By year", lambda r: r["day"][:4], None, dev, hold)
    table("By side", lambda r: "long" if r["side"] == 1 else "short", ["long", "short"], dev, hold)
    hour = bucket(["09:45", "10:00", "10:30", "11:30", "24:00"], ["09:35-09:44", "09:45-09:59", "10:00-10:29",
                                                                "10:30-11:29", "11:30+"])
    table("By entry time (New York)", lambda r: hour(r["at"]), ["09:35-09:44", "09:45-09:59", "10:00-10:29",
                                                                 "10:30-11:29", "11:30+"], dev, hold)
    rv = sorted(r["rel_vol"] for r in dev)
    q = [rv[len(rv) * i // 5] for i in range(1, 5)]
    rv_labels = [f"Q{i + 1}" for i in range(5)]
    table("By opening relative volume (development quintiles)", lambda r: bucket(q + [math.inf], rv_labels)(r["rel_vol"]),
          rv_labels, dev, hold, f"Quintile edges from development: {', '.join(f'{x:.2f}' for x in q)}.")
    table("By rank in the top 20", lambda r: bucket([6, 11, 16, 99], ["1-5", "6-10", "11-15", "16-20"])(r["rank"]),
          ["1-5", "6-10", "11-15", "16-20"], dev, hold)
    price = bucket([10, 20, 50, math.inf], ["<$10", "$10-20", "$20-50", "$50+"])
    table("By price at entry", lambda r: price(r["fill"]), ["<$10", "$10-20", "$20-50", "$50+"], dev, hold)
    sp = bucket([0.10, 0.15, 0.20, math.inf], ["<0.10", "0.10-0.15", "0.15-0.20", "0.20-0.25"])
    table("By spread at the trigger / stop distance", lambda r: sp(r["spread_d"]),
          ["<0.10", "0.10-0.15", "0.15-0.20", "0.20-0.25"], dev, hold)
    vol = bucket([0.03, 0.05, 0.08, math.inf], ["<3%", "3-5%", "5-8%", "8%+"])
    table("By volatility (ATR14 / price)", lambda r: vol(r["atr_pct"]), ["<3%", "3-5%", "5-8%", "8%+"], dev, hold)
    slip = bucket([0.0001, 0.1, 0.5, math.inf], ["0", "0-0.1R", "0.1-0.5R", "0.5R+"])
    table("By entry slippage beyond the stop level (tick-level fill, in R)", lambda r: slip(r["slip"]),
          ["0", "0-0.1R", "0.1-0.5R", "0.5R+"], dev, hold)
    print("\n### Entry slippage beyond the stop level (in R), by year\n\n| Year | Trades | Mean | Median | Share > 0 |"
          "\n|---|---:|---:|---:|---:|")
    for y in sorted({r["day"][:4] for r in dev + hold}):
        xs = [r["slip"] for r in dev + hold if r["day"][:4] == y]
        print(f"| {y} | {len(xs)} | {statistics.mean(xs):+.3f} | {statistics.median(xs):+.3f} | "
              f"{sum(x > 1e-9 for x in xs) / len(xs):.0%} |")
    print("\n### Concentration\n\n| Set | Trades | Total R | Top 1% | Top 5% | Total without top 1% | Trades ≥ 5R "
          "| Their mean | Mean of the rest | Best |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    print(concentration("Development", dev))
    print(concentration("Holdout", hold))
    for y in sorted({r["day"][:4] for r in dev + hold}):
        print(concentration(y, [r for r in dev + hold if r["day"][:4] == y]))
    for name, rows in (("Development", dev), ("Holdout", hold)):
        m = monthly(rows)
        vals = sorted(m.items(), key=lambda kv: kv[1])
        total = sum(m.values())
        worst = vals[:5]
        best = vals[-5:][::-1]
        print(f"\n### Months: {name}\n\nMonths {len(m)}, positive {sum(v > 0 for v in m.values())}, total "
              f"{total:+.1f}R. Worst 5: " + ", ".join(f"{k} {v:+.1f}" for k, v in worst) + f" (sum "
              f"{sum(v for _, v in worst):+.1f}). Best 5: " + ", ".join(f"{k} {v:+.1f}" for k, v in best)
              + f" (sum {sum(v for _, v in best):+.1f}).")
    print("\n### Exits that were not stopped (held to the close)\n\n| Set | Trades | Share | Mean net R | Median net R |"
          " Mean when the stop was hit |\n|---|---:|---:|---:|---:|---:|")
    for name, rows in (("Development", dev), ("Holdout", hold)):
        eod = [r["net_r"] for r in rows if r["kinds"] != "stop"]
        st = [r["net_r"] for r in rows if r["kinds"] == "stop"]
        print(f"| {name} | {len(eod)} | {len(eod) / len(rows):.0%} | {statistics.mean(eod):+.3f} | "
              f"{statistics.median(eod):+.3f} | {statistics.mean(st):+.3f} |")
    print("\n### The opposite side (net_r_short: the same fill, the other direction)\n\n| Set | Mean | Win |\n|---|---:|---:|")
    for name, rows in (("Development", dev), ("Holdout", hold)):
        xs = [r["net_r_short"] for r in rows]
        print(f"| {name} | {statistics.mean(xs):+.3f} | {sum(x > 0 for x in xs) / len(xs):.0%} |")
    print("\n### Repeated tickers\n")
    for name, rows in (("Development", dev), ("Holdout", hold)):
        c = collections.Counter(r["t"] for r in rows)
        top = c.most_common(5)
        print(f"- {name}: {len(c)} tickers; most traded " + ", ".join(f"{t} {n}" for t, n in top)
              + f"; the 5 most traded carry {sum(r['net_r'] for r in rows if r['t'] in dict(top)):+.1f}R.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
